### ISSUE TITLE
Invalid plugin specification moor_ffi. Cannot find the `flutter.plugin.platforms` key in the `pubspec.yaml` file

### ISSUE THREAD

**Issue by umutaktas** [kriticalflare/SIES-Library#1]
When I debug code, I got an error on below. I updated moor,moor_ffi and moor_generator versions but I've got different errors .

` Invalid plugin specification moor_ffi. Cannot find the `flutter.plugin.platforms` key in the `pubspec.yaml` file`

**Comment by kriticalflare** [comment]
@umutaktas the issue seems to be similar to https://github.com/simolus3/moor/issues/727#issuecomment-662935493. You are free to make a PR if you want to as a part of Hacktoberfest :) 
According to the issue link given above and the package's [pub.dev](https://pub.dev/packages/moor_ffi) page you can just remove moor_ffi from your dependencies and add sqlite3_flutter_libs instead. Also, replace the following imports:

    change package:moor_ffi/moor_ffi.dart to package:moor/ffi.dart
    change package:moor_ffi/open_helper.dart to package:sqlite3/open.dart

**Comment by umutaktas** [comment]
> @umutaktas the issue seems to be similar to [simolus3/moor#727 (comment)](https://github.com/simolus3/moor/issues/727#issuecomment-662935493). You are free to make a PR if you want to as a part of Hacktoberfest :)
> According to the issue link given above and the package's [pub.dev](https://pub.dev/packages/moor_ffi) page you can just remove moor_ffi from your dependencies and add sqlite3_flutter_libs instead. Also, replace the following imports:
> 
> ```
> change package:moor_ffi/moor_ffi.dart to package:moor/ffi.dart
> change package:moor_ffi/open_helper.dart to package:sqlite3/open.dart
> ```

Thanks. Problem solved.
